### ISSUE TITLE
Door sensor state 66

### ISSUE THREAD

**Issue by dmoeyers** [jbouwh/lib-elro-connects#18]
Hello,

first all of thank you for this Elro integration. I noticed a new state available for a door sensor. It seems when the door goes open, it goes to state ALARM, but only for a minute. Then it switches to state 66.
In the Elro app it was shown in green (first time I notice this), but when I actived away mode the alarm did sound.

Brgds
Dieter
![Screenshot 2022-09-05 at 09 35 54](https://user-images.githubusercontent.com/22577819/188395321-3968c539-c2af-4a71-b71f-9d38f4f19ef0.png)
![Screenshot 2022-09-05 at 09 33 13](https://user-images.githubusercontent.com/22577819/188395324-61b16990-344b-45cf-b5ed-d196a56608b5.png)

**Comment by jbouwh** [comment]
State 66 means the library does not support that state yet. This is because I did not yet test with door sensors.

Can you tell me what state state name state 66 should reflect?

**Comment by jbouwh** [comment]
To allign with the other sensor states, I will use the `NORMAL` state for state `66`. `ALARM` means the sensor was triggered by the opening. I'll open A PR to address this issue.

**Comment by jbouwh** [comment]
The latest release should now show `NORMAL` instead of `66`. Thnx for reporting.
https://github.com/jbouwh/ha-elro-connects/releases/tag/v0.1.11

**Comment by dmoeyers** [comment]
Hi Jan,

thanks for your very quick reaction!

I did an extra test and in my Elro app the sensor first shows 'Open' and then transitions to 'Blijft open' (with a red indication) after a minute. Strange because this morning it showed green and normal.  I think this has something to do with the note I red somewhere that the system can only communicate to either the app or either HA. Because now after another close/open cycle the app shows red 'Blijft open' while HA showed 'Alarm' and then '66' (with the old release).
So maybe 'Normal' state should only be reserved for closed?

Brgds

**Comment by jbouwh** [comment]
Let me know if state 66 should be something else than `NORMAL` as far as I know it is not used elsewhere. I cannot test it myself, but you could use the example script to get some more information about the data returned. Do not hesitate to open a new issue.

**Comment by dmoeyers** [comment]
Ok thank you Jan. I'm quite new to HA and have limited time now and leave on holiday, but afterwards I'm more than happy to help or test where I can...
